export const DEFAULT_MEDIAN_REFRESH_SECONDS = 30;
export const MIN_GUESS_VALUE = 0;
export const MAX_GUESS_VALUE = 100;
export const DEFAULT_GUESS_JUSTIFICATION_MAX_LENGTH = 500;
export const DEFAULT_GAME_DURATIONS_MINUTES = [60, 180, 360, 1440];
export const DEFAULT_PAGINATION_LIMIT = 20;

